apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ryahmft1w-python
  janus-idp.io/tekton: ryahmft1w-python
  backstage.io/kubernetes-id: ryahmft1w-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ryahmft1w-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
