apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ryahmft1w-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ryahmft1w-python 
  name: ryahmft1w-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ryahmft1w-python 
